### ISSUE TITLE
libadalang test runner on Windows with Python3.8+ cannot find dlls

### ISSUE THREAD

**Issue by LordAro** [AdaCore/langkit#579]
Seems that Python changed how it handles dll dependencies in 3.8, and now extra paths need to be added explicitly:
https://docs.python.org/3/library/os.html#os.add_dll_directory

Currently it fails with a message something along the lines of:
```
Traceback (most recent call last):
  File "C:\libadalang\tmp\name_resolution__S709-005\test.py", line 1, in <module>
    import libadalang as lal
  File "C:\libadalang\build\python\libadalang\__init__.py", line 94, in <module>
    _c_lib = ctypes.cdll.LoadLibrary(_c_lib_path)
  File "C:\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libadalang.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

As a cheap and nasty hack, the following in module_py.mako just above the LoadLibrary call seems to work, but could probably be improved:

```python
for path in os.environ['PATH'].split(';'):
    if os.path.exists(path):
        os.add_dll_directory(path)
```

https://github.com/AdaCore/langkit/blob/d79dfd3cbc3325185e3f5d3a04cc495d76546198/langkit/templates/python_api/module_py.mako#L79

**Comment by pmderodat** [comment]
It seems that we will indeed need to do something similar. We’ll take care of it, thank you for bringing this to our attention!

**Comment by pmderodat** [comment]
Hello,

Some time ago, we introduced a `--generate-auto-dll-dirs` to `manage.py generate|make` commands (62b82450bdd7f9e11c559cc4151c8d671cd98f77) so that the generated code for Python bindings do the hack that you mentionned in your first message. We kept this behavior optional and disabled by default because we feel this defeats the purpose of Python’s 3.8 DLL lookup mechanism, so we likely won’t be able to do much more…
