### ISSUE TITLE
Wrong build values for VSS dependancy.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/langkit#654]
I got these errors:

```
% python3 manage.py build-langkit-support --library-types=static,static-pic,relocatable --build-mode=prod
prettier_ada.gpr:16:04: value "static" is illegal for typed string "build"
vss_gnat.gpr:5:04: value "static" is illegal for typed string "build"
vss_text.gpr:7:04: value "static" is illegal for typed string "build"
```
How to recover?
[Edited]
Obviously, by selecting only `relocatable`:
`% python3 manage.py build-langkit-support --library-types=relocatable --build-mode=prod`
Indeed, this comes from the fact that by default VSS makefile builds only `relocatable` lib. `build-all-lib` shouldn't be the default as other tools?

**Comment by pmderodat** [comment]
Hello,

This looks like all the Ada dependencies that are listed (prettier-ada, vss) were built and installed only in relocatable mode. Since it is invalid in gprbuild to have a mix of statically-linked and dynamically-linked library projects in the same tree, the request to build `Langkit_Support` in all link mode is invalid.

In principle, all AdaCore projects should be built as static libraries by default: if that’s not the case in VSS, it’s worth opening an issue directly in the VSS repository.
